### ISSUE TITLE
Config option for default .gitignore stack?

### ISSUE THREAD

**Issue by tedmiston** [simonwhitaker/gibo#23]
Do you have any thoughts on adding a default gibo config setting?

For example, I use the same .gitignore files most of the time for most projects, so it would be nice to be able to type something like

    $ gibo -d

vs

    $ gibo macOS SublimeText Python >> .gitignore

I setup an MVP of this with an alias in my `~/.bash_profile` for now:

    alias gibod="gibo macOS SublimeText Python >> .gitignore"

**Comment by simonwhitaker** [comment]
Ah, nice idea. I think it does make sense to just alias this though, rather than trying to make the tool smarter. Dumb tools are best. 😄

**Comment by tedmiston** [comment]
Cool.  For anyone who finds the issue in the future, another interesting idea would be hooking these "default" gibo args into cookiecutter, I think with a [pre/post-generate hook](http://cookiecutter.readthedocs.io/en/latest/advanced/hooks.html) to always have the latest combined .gitignore added to new projects.
