### ISSUE TITLE
[v2] Update gibo.bat to use subcommand model

### ISSUE THREAD

**Issue by simonwhitaker** [simonwhitaker/gibo#26]
gibo 2.0 adopts a subcommand model for its command line UI. Here's the relevant portion of the usage text:

```
Usage:
    gibo [command]

Example:
    gibo dump Swift Xcode >> .gitignore

Commands:
    list            List available boilerplates
    update          Update list of available boilerplates
    help            Display this help text
    version         Display current script version
    dump BOILERPLATE...
                    Write boilerplate(s) to STDOUT
```

The changes from v1.x are summarised as follows:

gibo 1.x | gibo 2.0
--------|---------
`gibo -h`, `gibo --help` | `gibo help`
`gibo -l`, `gibo --list` | `gibo list`
`gibo -u`, `gibo --upgrade` | `gibo update` (note the rename: upgrade -> update)
`gibo -v`, `gibo --version` | `gibo version`
`gibo BOILERPLATE` | `gibo dump BOILERPLATE`

**Comment by simonwhitaker** [comment]
@kodybrown Do you fancy having a go at this one? 😄

**Comment by simonwhitaker** [comment]
I had a go myself. Seems to work (Windows 10 VM, Git Bash). Please feel free to suggest any changes.

**Comment by kodybrown** [comment]
Hi @simonwhitaker. Your code looks good. I cleaned up a few things and added a couple new features to bring it up to par with the bash script. I actually had an old bit of code for a `search` command that I added also. I'll send a pull request.
