### ISSUE TITLE
confusing usage example

### ISSUE THREAD

**Issue by tsekineMcp** [simonwhitaker/gibo#37]
Hi,

This is an awesome tool to save the time to write gitignore.
I always use this tool when starting new projects.

By the way, let me tell you that the update for some parts of code seemed delayed.

The example seems the previous usage.
https://github.com/simonwhitaker/gibo/blob/ff9f2f807ecefefb4c93851cee4ab067a7c7988f/gibo.bat#L32

**Comment by simonwhitaker** [comment]
Nice catch, thanks!
