### ISSUE TITLE
Not available at COPR repository

### ISSUE THREAD

**Issue by maaattes** [simonwhitaker/gibo#42]
Hi,
currently the package is not available via the [COPR repository](https://copr.fedorainfracloud.org/coprs/saschpe/gibo/package/gibo/). The build failed and is out of date.

**Comment by simonwhitaker** [comment]
@saschpe Want to take a look at this one?

**Comment by saschpe** [comment]
It's missing for Fedora 30 indeed. I tried to include the package into Fedora's main repository but it's been a drag so far.

Another option would be to provide a [Flatpak](https://flathub.org/home) instead. That would make it easily available for many Linux distributions.

**Comment by saschpe** [comment]
By the way, it just works for me (tm) on Fedora 30:
```
$ dnf copr enable saschpe/gibo
$ gibo version
zsh: gibo: command not found...
Install package 'gibo' to provide command 'gibo'? [N/y] y
...
 * Installing packages... 
gibo 2.2.3 by Simon Whitaker <sw@netcetera.org>
https://github.com/simonwhitaker/gibo
```

**Comment by saschpe** [comment]
About the Flatpak'ed version, here we go https://github.com/flathub/flathub/pull/1118
