### ISSUE TITLE
setopt lines break when not run through bash

### ISSUE THREAD

**Issue by tsangal** [simonwhitaker/gibo#43]
https://github.com/simonwhitaker/gibo/blob/bd5710b9b3a7db6a08d9c1464e05b3f81deafccb/gibo#L6-L9

On my system (Linux Mint) /bin/sh is symlinked to dash. Thus, executing the gibo script directly from the command-line no longer works due the the "set -o" lines at the top of the script.

```
$ ./gibo update
./gibo: 9: set: Illegal option -o pipefail
```

I have to run it through bash explicitly (e.g. `bash gibo update`).

**Comment by simonwhitaker** [comment]
Oops, my bad. Thanks for reporting! Reverted in 090c376.
