### ISSUE TITLE
Release please ;-)

### ISSUE THREAD

**Issue by saschpe** [simonwhitaker/gibo#49]
It's been a while.

**Comment by simonwhitaker** [comment]
Was there something in particular you wanted pulled into a release, Sascha? I don't think there have been any significant changes since the last release, or am I missing something?

**Comment by saschpe** [comment]
Hi Simon,

> On 3. Mar 2020, at 23:22, Simon Whitaker <notifications@github.com> wrote:
> 
> Was there something in particular you wanted pulled into a release, Sascha? I don't think there have been any significant changes since the last release, or am I missing something?
> 

There’s no urge indeed. As soon as you have another tarball up on Github, I can remove the Flatpak configuration from this PR again [0].

[0] https://github.com/flathub/flathub/pull/1118 <https://github.com/flathub/flathub/pull/1118>
--
Mit freundlichen Grüßen,
Sascha Peilicke

**Comment by simonwhitaker** [comment]
Ah! Sorry, I hadn't realised that was waiting on me. I'll do a release now. :)

**Comment by simonwhitaker** [comment]
Done! https://github.com/simonwhitaker/gibo/releases/tag/2.2.4
