### ISSUE TITLE
Unknown Argument: {Boilerplate}

### ISSUE THREAD

**Issue by SubhoBoy** [simonwhitaker/gibo#53]
The following command 
```shell
gibo dump Python VisualStudioCode Windows >> .gitignore
```
yields
```shell
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
```
in the terminal, and `Unknown Argument: Python` (or VisualStudioCode or Windows) in the .gitignore file. The boilerplate heading also seems to be repeated, as
```gitignore
### Generated by gibo (https://github.com/simonwhitaker/gibo
### Python

{Boilerplate contents}


### Python



Unknown Argument: Python
### VisualStudioCode



### VisualStudioCode

{Boilerplate contents}


Unknown argument: VisualStudioCode
### Windows



### Windows

{Boilerplate contents}


Unknown Argument:Windows

```

OS: Windows 11 21H2 (Build 22000.588)
Gibo: 2.2.6 through scoop

**Comment by simonwhitaker** [comment]
Hi there. Thanks for the bug report! I believe this issue was fixed in #52. I will see if I can remember how to deploy an update to scoop! 😆

**Comment by simonwhitaker** [comment]
As of https://github.com/ScoopInstaller/Main/commit/838bba97d6a7abe792c10e994d7a46197abcf1e8 this fix should be live in scoop.

**Comment by SubhoBoy** [comment]
Yes, It's fine now. Thanks!
